### ISSUE TITLE
iOS builds not working

### ISSUE THREAD

**Issue by EduMenges** [rhuijben/sqlite-amalgamation#5]
The `gethostuuid` function has been removed in iOS, but CMake can't really detect that:

```cmake
check_function_exists(gethostuuid HAVE_GETHOSTUUID)
if(HAVE_GETHOSTUUID)
    add_definitions(-DHAVE_GETHOSTUUID=1)
endif()
```

Neither `check_function_exists` nor `check_symbol_exists` will work to detect this case, because while the symbol for `gethostuuid` exists, [it is marked with a Clang availability attribute in the header file](https://clang.llvm.org/docs/AttributeReference.html#availability), stopping the build.

A workaround is to just include a check in the conditional if the `CMAKE_SYSTEM_NAME` is not equals to `iOS`. A more precise check would also verify the SDK version to enable building using `gethostuuid` for old versions.

**Comment by EduMenges** [comment]
[I've made a fork to address this](https://github.com/GeniusVentures/sqlite-amalgamation).

**Comment by rhuijben** [comment]
Do you have a PR for me to fix this?

**Comment by rhuijben** [comment]
Ok, just merged your main branch of the repository. Thanks!

**Comment by rhuijben** [comment]
Thanks!
